#!/usr/bin/env bash

secret_access_token=$1

set_github_config() {
  git config --global user.name "GitHub Actions Bot"
  git config --global user.email "ecess@purdue.edu"
}

checkout_ambassadors() {
  mkdir out/ecea
  git reset --hard origin/ecea
  ls | grep -v out | xargs -t -I '{}' mv {} out/ecea
  touch out/ecea/.nojekyll
}

checkout_student_society() {
  git reset --hard origin/ecess
  ls | grep -v out | xargs -t -I '{}' mv {} out/
  touch out/.nojekyll
}

checkout_wece() {
  mkdir out/wece
  git reset --hard origin/wece
  ls | grep -v out | xargs -t -I '{}' mv {} out/wece
  touch out/wece/.nojekyll
}

checkout_spark() {
  mkdir out/spark
  git reset --hard origin/spark
  ls | grep -v out | xargs -t -I '{}' mv {} out/spark
  touch out/spark/.nojekyll
}

checkout_justin() {
  mkdir out/justin
  git reset --hard origin/justin
  ls | grep -v out | xargs -t -I '{}' mv {} out/justin
  touch out/justin/.nojekyll
}

add_cname_file() {
  echo "www.purdue-ecess.org" > out/CNAME
}

push_to_gh_pages() {
  cd out
  git init
  git add .
  set_github_config
  git commit -m "Deployment of Purdue Student Society Websites"
  git branch -m gh-pages
  git remote add origin https://x-access-token:"$secret_access_token"@github.com/Purdue-ECESS/website
  git push origin gh-pages --force
  cd ../
}

rm -rf out
mkdir out
cp 404.html out/404.html
checkout_ambassadors
checkout_student_society
checkout_wece
checkout_spark
checkout_justin
add_cname_file
push_to_gh_pages
git reset --hard origin/main
