#!/usr/bin/env bash

secret_access_token=$1

set_github_config() {
  git config --global user.name "GitHub Actions Bot"
  git config --global user.email "ecess@purdue.edu"
}

checkout_ambassadors() {
  mkdir out/ecea
  git reset --hard origin/ecea
  ls | grep -v out | xargs -t -I '{}' mv {} out/ecea
  touch out/ecea/.nojekyll
}

checkout_student_society() {
  echo "<p>ECESS Website in Development</p>" > out/index.html
}

checkout_wece() {
  mkdir out/wece
  git reset --hard origin/wece
  ls | grep -v out | xargs -t -I '{}' mv {} out/wece
  touch out/wece/.nojekyll
}

add_cname_file() {
  echo "www.purdue-ecess.org" > out/CNAME
  touch out/.nojekyll
}

push_to_gh_pages() {
  cd out
  git init
  git add * .nojekyll
  set_github_config
  git commit -m "Deployment of Purdue Student Society Websites"
  git branch -m gh-pages
  git remote add origin https://x-access-token:"$secret_access_token"@github.com/Purdue-ECESS/website
  echo "Force GH Pages to Production"
  git push origin gh-pages --force
  cd ../
}

rm -rf out
mkdir out
checkout_ambassadors
checkout_student_society
checkout_wece
add_cname_file
push_to_gh_pages
git reset --hard origin/main